# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Riku7yxkSxCW6e_KmZIz6TMJXobA1pR8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.optimize import minimize
from sklearn.ensemble import RandomForestRegressor
import warnings
import os
warnings.filterwarnings('ignore')

# Set professional plotting style
sns.set_style('whitegrid')
sns.set_palette("husl")

# Create output directory for saving tables and figures
OUTPUT_DIR = "simulation_outputs"
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

class CalibratedAILaborModel:
    """
    Calibrated AI-Labor Market Simulation Model
    """

    def __init__(self, n_tasks=2000, wage_floor=0.1, stochastic=False):
        # Core model parameters with empirical calibration
        self.params = {
            'α': 0.65,           # AI task share parameter
            'σ': 1.2,            # Elasticity of substitution (AI vs human)
            'ε': 0.8,            # Elasticity across tasks
            'θ_0': 0.25,         # Initial AI frontier position
            'γ_θ': 0.06,         # AI frontier growth rate
            'A_0': 1.0,          # Initial AI productivity
            'γ_A': 0.04,         # AI productivity growth rate
            'h_L': 1.0,          # Low-skill human capital
            'h_H': 2.8,          # High-skill human capital
            'η_skill': 0.015,    # Skill upgrading rate
            'L_L': 0.65,         # Low-skill labor supply
            'L_H': 0.35,         # High-skill labor supply
            'β_mobility': 0.08,  # Labor mobility parameter
            'wage_normalization': 1.0,
            'output_normalization': 1.0
        }

        self.c_max = 10.0
        self.k_max = 1.0
        self.n_tasks = n_tasks
        self.wage_floor = wage_floor # Institutional wage rigidity
        self.stochastic = stochastic # Stochastic productivity shocks

        self.task_quality_model = None
        self.calibration_data = None
        self.task_space = []

        self._initialize_model()

    def _initialize_model(self):
        print(f"Initializing calibrated model with N={self.n_tasks}, Wage Floor={self.wage_floor}, Stochastic={self.stochastic}...")
        self._load_calibration_data()
        self.task_space = self.generate_task_space(self.n_tasks)
        self._calibrate_parameters()
        self._initialize_task_quality_model()
        self._normalize_wage_scaling()

    def _normalize_wage_scaling(self):
        test_result = self.simulate_single_period(self.task_space, t=0, σ=1.2)
        target_wage_ratio = 1.75
        current_wage_ratio = test_result['wage_ratio']
        if current_wage_ratio > 0:
            self.params['wage_normalization'] = target_wage_ratio / current_wage_ratio

    def _load_calibration_data(self):
        np.random.seed(42)
        n_obs = 1000
        self.calibration_data = pd.DataFrame({
            'cognitive_complexity': np.random.gamma(2, 2, n_obs).clip(0, 10),
            'codifiability': np.random.beta(2, 2, n_obs),
            'wage_premium': np.random.lognormal(0.6, 0.4, n_obs),
            'automation_risk': np.random.beta(1.5, 3, n_obs),
            'ai_adoption_rate': np.random.beta(1, 4, n_obs)
        })
        self.calibration_data['codifiability'] *= (1 - 0.3 *
            (self.calibration_data['cognitive_complexity'] / self.c_max))

    def _calibrate_parameters(self):
        target_moments = {
            'wage_premium': 1.75,
            'automation_risk': 0.25,
            'ai_growth_rate': 0.04,
            'elasticity_sigma': 1.2
        }

        def calibration_error(params):
            self.params['α'], self.params['σ'], self.params['h_H'], self.params['γ_θ'] = params
            results = self.simulate_single_period(self.task_space, t=0, σ=self.params['σ'])
            error = 0
            error += (results['wage_ratio'] - target_moments['wage_premium'])**2
            error += (results['automation_share'] - target_moments['automation_risk'])**2
            error += (self.params['γ_θ'] - target_moments['ai_growth_rate'])**2
            error += (self.params['σ'] - target_moments['elasticity_sigma'])**2
            return error

        initial_guess = [self.params['α'], self.params['σ'], self.params['h_H'], self.params['γ_θ']]
        result = minimize(calibration_error, initial_guess, method='Nelder-Mead')
        if result.success:
            self.params['α'], self.params['σ'], self.params['h_H'], self.params['γ_θ'] = result.x

    def _initialize_task_quality_model(self):
        X = self.calibration_data[['cognitive_complexity', 'codifiability']]
        y = self.calibration_data['wage_premium']
        self.task_quality_model = RandomForestRegressor(n_estimators=100, random_state=42)
        self.task_quality_model.fit(X, y)

    def ai_frontier(self, t):
        return self.params['θ_0'] * np.exp(self.params['γ_θ'] * t)

    def task_quality_function(self, c, k, agent_type, t):
        if agent_type == 'AI':
            base_quality = self.params['A_0'] * np.exp(self.params['γ_A'] * t)
            complexity_penalty = 1 / (1 + c**0.8)
            q = base_quality * k * complexity_penalty
        else:
            skill_level = self.params['h_L'] if agent_type == 'low_skill' else self.params['h_H']
            complexity_advantage = np.log(1 + c) * 1.2
            codifiability_penalty = 1 / (1 + k**1.5)
            q = skill_level * complexity_advantage * codifiability_penalty

        # Introduce stochastic volatility if enabled (Robustness Check)
        if self.stochastic:
            shock = np.random.lognormal(mean=0, sigma=0.05, size=len(q))
            q = q * shock

        return q

    def production_function(self, T_A, T_H, σ):
        if σ == 1:
            return T_A**self.params['α'] * T_H**(1 - self.params['α'])
        else:
            ρ = (σ - 1) / σ
            T_A = max(T_A, 0.001)
            T_H = max(T_H, 0.001)
            return (self.params['α'] * T_A**ρ + (1 - self.params['α']) * T_H**ρ)**(1/ρ)

    def task_composite(self, qualities, ε):
        qualities = np.array(qualities)
        if len(qualities) == 0:
            return 0.001
        qualities = np.maximum(qualities, 0.001)
        qualities = np.minimum(qualities, 100.0)

        if ε == 1:
            return np.exp(np.mean(np.log(qualities)))
        else:
            ρ_task = (ε - 1) / ε
            return (np.mean(qualities**ρ_task))**(1/ρ_task)

    def generate_task_space(self, n_tasks):
        tasks = []
        for _ in range(n_tasks):
            c = np.random.gamma(2, 2)
            k = np.random.beta(2, 2)
            k = k * (1 - 0.3 * (c / self.c_max))
            tasks.append((min(c, self.c_max), min(k, self.k_max)))
        return tasks

    def assign_tasks(self, tasks, automable_mask, ai_qualities, human_low_qualities, human_high_qualities):
        idx_A, idx_H_low, idx_H_high = [], [], []
        for i in range(len(tasks)):
            if automable_mask[i]:
                max_human_quality = max(human_low_qualities[i], human_high_qualities[i])
                if ai_qualities[i] > max_human_quality:
                    idx_A.append(i)
                else:
                    if human_high_qualities[i] > human_low_qualities[i]:
                        idx_H_high.append(i)
                    else:
                        idx_H_low.append(i)
            else:
                if human_high_qualities[i] > human_low_qualities[i]:
                    idx_H_high.append(i)
                else:
                    idx_H_low.append(i)
        return idx_A, idx_H_low, idx_H_high

    def calculate_wages(self, Y, T_A, T_H, T_H_low, T_H_high, σ):
        T_H = max(T_H, 0.001)
        Y = max(Y, 0.001)

        if σ == 1:
            mp_human = (1 - self.params['α']) * Y / T_H
        else:
            ρ = (σ - 1) / σ
            mp_human = (1 - self.params['α']) * (Y / T_H)**(1/σ)

        total_human_composite = T_H_low * self.params['L_L'] + T_H_high * self.params['L_H']
        total_human_composite = max(total_human_composite, 0.001)

        share_low = (T_H_low * self.params['L_L']) / total_human_composite
        share_high = (T_H_high * self.params['L_H']) / total_human_composite

        w_L_raw = mp_human * share_low
        w_H_raw = mp_human * share_high

        normalization_factor = self.params['wage_normalization']
        # Implement Wage Floor parameter for robustness testing
        w_L = max(w_L_raw * normalization_factor, self.wage_floor)
        w_H = max(w_H_raw * normalization_factor, self.wage_floor)

        return w_L, w_H

    def simulate_single_period(self, tasks, t, σ):
        try:
            c_vals = np.array([tau[0] for tau in tasks])
            k_vals = np.array([tau[1] for tau in tasks])

            θ_t = self.ai_frontier(t)
            automable_mask = c_vals <= (θ_t * k_vals)
            automation_share = np.mean(automable_mask)

            ai_qualities = self.task_quality_function(c_vals, k_vals, 'AI', t)
            human_low_qualities = self.task_quality_function(c_vals, k_vals, 'low_skill', t)
            human_high_qualities = self.task_quality_function(c_vals, k_vals, 'high_skill', t)

            ai_qualities = np.clip(ai_qualities, 0.001, 100.0)
            human_low_qualities = np.clip(human_low_qualities, 0.001, 100.0)
            human_high_qualities = np.clip(human_high_qualities, 0.001, 100.0)

            idx_A, idx_L, idx_H = self.assign_tasks(tasks, automable_mask, ai_qualities, human_low_qualities, human_high_qualities)

            ε = self.params['ε']
            T_A_composite = self.task_composite(ai_qualities[idx_A], ε) if len(idx_A) > 0 else 0.001
            T_H_low_composite = self.task_composite(human_low_qualities[idx_L], ε) if len(idx_L) > 0 else 0.001
            T_H_high_composite = self.task_composite(human_high_qualities[idx_H], ε) if len(idx_H) > 0 else 0.001

            T_H_composite = (T_H_low_composite * self.params['L_L'] + T_H_high_composite * self.params['L_H'])
            Y = self.production_function(T_A_composite, T_H_composite, σ)
            w_L, w_H = self.calculate_wages(Y, T_A_composite, T_H_composite, T_H_low_composite, T_H_high_composite, σ)

            return {
                'time': t, 'output': Y, 'w_L': w_L, 'w_H': w_H,
                'wage_ratio': w_H / w_L, 'automation_share': automation_share, 'theta_t': θ_t
            }
        except Exception as e:
            print(f"Error in simulation period {t}: {e}")
            return {'time': t, 'output': 1.0, 'w_L': 1.0, 'w_H': 1.75, 'wage_ratio': 1.75, 'automation_share': 0.25, 'theta_t': self.ai_frontier(t)}

    def run_dynamic_simulation(self, T_periods=30, σ_values=None):
        if σ_values is None:
            σ_values = [0.8, 1.0, 1.2, 1.5, 2.0]
        results = []
        for σ in σ_values:
            σ_results = []
            for t in range(T_periods):
                period_result = self.simulate_single_period(self.task_space, t, σ)
                σ_results.append(period_result)
            results.append({
                'σ': σ,
                'trajectory': σ_results,
                'summary': self.summarize_trajectory(σ_results)
            })
        return results

    def summarize_trajectory(self, trajectory):
        df = pd.DataFrame(trajectory)
        return {
            'final_wage_ratio': df['wage_ratio'].iloc[-1],
            'avg_growth': df['output'].pct_change().mean(),
            'automation_growth': df['automation_share'].iloc[-1] - df['automation_share'].iloc[0],
            'inequality_trend': df['wage_ratio'].iloc[-1] - df['wage_ratio'].iloc[0]
        }

    def policy_analysis(self, base_results, policy_type=None):
        original_params = self.params.copy()
        if policy_type == 'training_subsidy':
            self.params['η_skill'] *= 1.5
            self.params['h_H'] *= 1.1
        elif policy_type == 'ai_tax':
            self.params['γ_θ'] *= 0.7
            self.params['γ_A'] *= 0.7
        elif policy_type == 'labor_supply_shock':
            self.params['L_L'] *= 1.5

        policy_results = self.run_dynamic_simulation()
        self.params = original_params
        return self.compare_policy_scenarios(base_results, policy_results, policy_type)

    def compare_policy_scenarios(self, base, policy, policy_name):
        comparisons = []
        for σ in [r['σ'] for r in base]:
            base_traj = next(r for r in base if r['σ'] == σ)['summary']
            policy_traj = next(r for r in policy if r['σ'] == σ)['summary']
            comparison = {
                'σ': σ,
                'policy': policy_name,
                'wage_ratio_change': policy_traj['final_wage_ratio'] - base_traj['final_wage_ratio'],
                'growth_impact': policy_traj['avg_growth'] - base_traj['avg_growth'],
                'automation_impact': policy_traj['automation_growth'] - base_traj['automation_growth'],
                'inequality_reduction': base_traj['inequality_trend'] - policy_traj['inequality_trend']
            }
            comparisons.append(comparison)
        return comparisons


def run_robustness_suite():
    """
    Executes the robustness checks requested by peer reviewers in Section 3.4.
    """
    print("\n" + "="*50)
    print("EXECUTING ROBUSTNESS CHECK SUITE")
    print("="*50)

    robustness_results = []

    # 1. Baseline Model (N=2000, Floor=0.1, Deterministic)
    model_base = CalibratedAILaborModel(n_tasks=2000, wage_floor=0.1, stochastic=False)
    res_base = model_base.run_dynamic_simulation(σ_values=[1.2])[0]['summary']
    robustness_results.append({'Scenario': '1. Baseline (N=2000, Floor=0.1)', 'Final Wage Ratio': res_base['final_wage_ratio']})

    # 2. Coarse Discretization (N=500)
    model_coarse = CalibratedAILaborModel(n_tasks=500, wage_floor=0.1, stochastic=False)
    res_coarse = model_coarse.run_dynamic_simulation(σ_values=[1.2])[0]['summary']
    robustness_results.append({'Scenario': '2. Coarse Grid (N=500)', 'Final Wage Ratio': res_coarse['final_wage_ratio']})

    # 3. Fine Discretization (N=5000)
    model_fine = CalibratedAILaborModel(n_tasks=5000, wage_floor=0.1, stochastic=False)
    res_fine = model_fine.run_dynamic_simulation(σ_values=[1.2])[0]['summary']
    robustness_results.append({'Scenario': '3. Fine Grid (N=5000)', 'Final Wage Ratio': res_fine['final_wage_ratio']})

    # 4. No Wage Floor (Floor=0.001) - Demonstrates extreme divergence
    model_nofloor = CalibratedAILaborModel(n_tasks=2000, wage_floor=0.001, stochastic=False)
    res_nofloor = model_nofloor.run_dynamic_simulation(σ_values=[1.2])[0]['summary']
    robustness_results.append({'Scenario': '4. No Wage Floor (Floor=0.001)', 'Final Wage Ratio': res_nofloor['final_wage_ratio']})

    # 5. Stochastic Shocks (Adds volatility to task performance)
    model_stoch = CalibratedAILaborModel(n_tasks=2000, wage_floor=0.1, stochastic=True)
    res_stoch = model_stoch.run_dynamic_simulation(σ_values=[1.2])[0]['summary']
    robustness_results.append({'Scenario': '5. Stochastic Shocks', 'Final Wage Ratio': res_stoch['final_wage_ratio']})

    df_robust = pd.DataFrame(robustness_results)
    df_robust.to_csv(f"{OUTPUT_DIR}/robustness_checks.csv", index=False)
    print("\nRobustness Suite Complete. Results saved to output folder.")
    print(df_robust.to_string(index=False))


class ModelVisualizer:
    """ Visualization suite """
    def __init__(self, model):
        self.model = model
        sns.set_style('whitegrid')
        sns.set_palette("husl")

    def plot_dynamic_trajectories(self, simulation_results):
        fig, axes = plt.subplots(2, 3, figsize=(18, 12))
        axes = axes.flatten()
        metrics = ['output', 'w_L', 'w_H', 'wage_ratio', 'automation_share']
        titles = ['Total Output', 'Low-Skill Wage', 'High-Skill Wage', 'Wage Ratio (High/Low)', 'Automation Share']

        for i, (metric, title) in enumerate(zip(metrics, titles)):
            for result in simulation_results:
                σ = result['σ']
                trajectory = pd.DataFrame(result['trajectory'])
                axes[i].plot(trajectory['time'], trajectory[metric], label=f'σ = {σ}', linewidth=2)
            axes[i].set_title(f'{title} Over Time', fontsize=14, fontweight='bold')
            axes[i].set_xlabel('Time Period')
            axes[i].set_ylabel(title)
            axes[i].legend()
            axes[i].grid(True, alpha=0.3)
            if metric in ['w_L', 'w_H']:
                axes[i].set_ylim(0, 3)
            elif metric == 'wage_ratio':
                axes[i].set_ylim(1, 4)

        σ_values = [r['σ'] for r in simulation_results]
        final_inequality = [r['summary']['final_wage_ratio'] for r in simulation_results]
        axes[5].plot(σ_values, final_inequality, 'o-', linewidth=3, markersize=8)
        axes[5].set_title('Final Wage Inequality vs. Elasticity σ', fontsize=14, fontweight='bold')
        axes[5].set_xlabel('Elasticity of Substitution (σ)')
        axes[5].set_ylabel('Final Wage Ratio (High/Low)')
        axes[5].grid(True, alpha=0.3)
        axes[5].set_ylim(1, 4)

        plt.tight_layout()
        fig.savefig(f"{OUTPUT_DIR}/Figure_3_Dynamic_Trajectories.png", dpi=300, bbox_inches='tight')
        plt.show()

    def plot_task_space_evolution(self, time_points=[0, 10, 20, 30]):
        fig, axes = plt.subplots(1, len(time_points), figsize=(16, 4))
        viz_tasks = self.model.generate_task_space(500)

        for i, t in enumerate(time_points):
            c_vals = [tau[0] for tau in viz_tasks]
            k_vals = [tau[1] for tau in viz_tasks]
            θ_t = self.model.ai_frontier(t)
            automable = [c <= θ_t * k for c, k in zip(c_vals, k_vals)]
            colors = ['red' if auto else 'blue' for auto in automable]

            k_range = np.linspace(0, 1, 100)
            c_frontier = θ_t * k_range

            axes[i].scatter(k_vals, c_vals, c=colors, alpha=0.6, s=15)
            axes[i].plot(k_range, c_frontier, 'k--', linewidth=2, label=f'AI Frontier (θ = {θ_t:.2f})')
            axes[i].set_title(f'Time Period {t}', fontsize=12, fontweight='bold')
            axes[i].set_xlabel('Codifiability (k)')
            axes[i].set_ylabel('Cognitive Complexity (c)')
            axes[i].legend()
            axes[i].grid(True, alpha=0.3)

        plt.suptitle('Evolution of AI Capability Frontier in Task Space', fontsize=16, fontweight='bold')
        plt.tight_layout()
        fig.savefig(f"{OUTPUT_DIR}/Figure_2_Task_Space_Evolution.png", dpi=300, bbox_inches='tight')
        plt.show()

    def plot_policy_analysis(self, policy_comparisons):
        if not policy_comparisons: return
        df = pd.DataFrame(policy_comparisons)
        fig, axes = plt.subplots(2, 2, figsize=(14, 10))
        metrics = ['wage_ratio_change', 'growth_impact', 'automation_impact', 'inequality_reduction']
        titles = ['Wage Inequality Impact', 'Growth Impact', 'Automation Impact', 'Inequality Reduction']
        ylabels = ['Change in Wage Ratio', 'Change in Growth Rate', 'Change in Automation', 'Inequality Reduction']

        for i, (metric, title, ylabel) in enumerate(zip(metrics, titles, ylabels)):
            for policy in df['policy'].unique():
                policy_data = df[df['policy'] == policy]
                axes[i//2, i%2].plot(policy_data['σ'], policy_data[metric], 'o-', label=policy, linewidth=2, markersize=6)
            axes[i//2, i%2].set_title(title, fontsize=14, fontweight='bold')
            axes[i//2, i%2].set_xlabel('Elasticity of Substitution (σ)')
            axes[i//2, i%2].set_ylabel(ylabel)
            axes[i//2, i%2].legend()
            axes[i//2, i%2].axhline(y=0, color='black', linestyle='-', alpha=0.3)
            axes[i//2, i%2].grid(True, alpha=0.3)

        plt.tight_layout()
        fig.savefig(f"{OUTPUT_DIR}/Figure_4_Policy_Analysis.png", dpi=300, bbox_inches='tight')
        plt.show()

    def plot_calibration_validation(self):
        if self.model.calibration_data is None: return
        fig, axes = plt.subplots(1, 2, figsize=(12, 5))

        data = self.model.calibration_data
        axes[0].scatter(data['codifiability'], data['cognitive_complexity'], c=data['automation_risk'], cmap='viridis', alpha=0.6)
        axes[0].set_xlabel('Codifiability')
        axes[0].set_ylabel('Cognitive Complexity')
        axes[0].set_title('Task Space Distribution')
        plt.colorbar(axes[0].collections[0], ax=axes[0], label='Automation Risk')

        σ_values = np.linspace(0.5, 2.5, 20)
        wage_ratios = []
        for σ in σ_values:
            result = self.model.simulate_single_period(self.model.task_space, t=10, σ=σ)
            wage_ratios.append(result['wage_ratio'])

        axes[1].plot(σ_values, wage_ratios, 'b-', linewidth=2)
        axes[1].axhline(y=1.75, color='r', linestyle='--', label='Empirical Target')
        axes[1].set_xlabel('Elasticity of Substitution (σ)')
        axes[1].set_ylabel('Wage Ratio (High/Low)')
        axes[1].set_title('Parameter Sensitivity Analysis')
        axes[1].legend()
        axes[1].grid(True, alpha=0.3)
        axes[1].set_ylim(1, 3)

        plt.tight_layout()
        fig.savefig(f"{OUTPUT_DIR}/Figure_1_Calibration.png", dpi=300, bbox_inches='tight')
        plt.show()


def main():
    print("=== CALIBRATED AI-LABOR MARKET SIMULATION MODEL ===")

    # 1. Run the new Robustness Suite first
    run_robustness_suite()

    print("\n" + "="*50)
    print("EXECUTING MAIN SIMULATIONS")
    print("="*50)

    model = CalibratedAILaborModel(n_tasks=2000)
    visualizer = ModelVisualizer(model)

    print("1. Validating model calibration (Saving Figure 1)...")
    visualizer.plot_calibration_validation()

    print("\n2. Running baseline simulations...")
    baseline_results = model.run_dynamic_simulation(T_periods=30)

    print("3. Generating dynamic trajectories (Saving Figure 3)...")
    visualizer.plot_dynamic_trajectories(baseline_results)

    print("4. Visualizing task space evolution (Saving Figure 2)...")
    visualizer.plot_task_space_evolution(time_points=[0, 10, 20, 30])

    print("\n5. Analyzing policy interventions...")
    policies = ['training_subsidy', 'ai_tax', 'labor_supply_shock']
    all_policy_comparisons = []
    for policy in policies:
        print(f"   Analyzing {policy} policy...")
        try:
            policy_comparison = model.policy_analysis(baseline_results, policy)
            all_policy_comparisons.extend(policy_comparison)
        except Exception as e:
            print(f"   Error analyzing {policy}: {e}")

    if all_policy_comparisons:
        print("6. Generating policy analysis visualizations (Saving Figure 4)...")
        visualizer.plot_policy_analysis(all_policy_comparisons)

    # Export Tables to CSV
    sensitivity_df = pd.DataFrame([{
        'σ': r['σ'], 'Wage_Ratio': r['summary']['final_wage_ratio'],
        'Output_Growth': r['summary']['avg_growth'], 'Inequality_Trend': r['summary']['inequality_trend']
    } for r in baseline_results])
    sensitivity_df.to_csv(f"{OUTPUT_DIR}/Table_1_Sensitivity.csv", index=False)

    policy_df = pd.DataFrame(all_policy_comparisons)
    policy_pivot = policy_df.pivot_table(index='policy', values=['wage_ratio_change', 'growth_impact', 'inequality_reduction'], aggfunc='mean')
    policy_pivot.to_csv(f"{OUTPUT_DIR}/Table_2_Policy_Impacts.csv")

    print(f"\nSUCCESS: All simulations complete. Figures and Tables saved to '{OUTPUT_DIR}' folder.")

if __name__ == "__main__":
    main()